# Generated by Django 4.2.3 on 2024-09-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
