services:
  web:
    build: ./app
    command: sh
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true         # Allocate a pseudo-TTY    
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev


#    command: python manage.py runserver 0.0.0.0:8000      